# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "geerlingguy/centos7"
  
    config.vm.provider "virtualbox" do |v|
      v.name = "postgresql"
      v.memory = 2048
      v.cpus = 2
    end
  
    config.vm.network "private_network", ip: "192.168.50.4"
    config.vm.synced_folder "project/", "/vagrant",
      create: true,
      type: "virtualbox",
      SharedFoldersEnableSymlinksCreate: false
  
    config.vm.provision "shell", path: "bootstrap.sh"
  end
  